### PR TITLE
Fix luna-load-default-font

### PR DESCRIPTION
**Pull request by dalugm**
Translate selected font-name to corresponding font-spec

### CODE REVIEW

**Comment by casouri** [comment]
Thank you very much!

**Comment by casouri** [comment]
Actually, I should've read it more closely. I think you want to use `luna-load-default-font` directly with a font name? You don't have to change `luna-load-default-font`, you can just use `luna-load-font` with a `default` face. And the change to `luna-load-default-font` broke `luna-load-font`.

So I've partially reverted the change to `luna-load-default-font`, to make it take a font-spec again.

**Comment by dalugm** [comment]
> I think you want to use `luna-load-default-font` directly with a font name?

I didn't get it... Before I change, the code is this:

```elisp
(defun luna-load-default-font (font-spec size &rest attrs)
  "Set font for default face to FONT-SPEC with SIZE and ATTRS.
See ‘luna-load-font’."
  ;; We use a separate function for default font because Emacs has a
  ;; bug that prevents us from setting a fontset for the default face
  ;; (although ‘set-frame-parameter’ works). So we just set default
  ;; face with ASCII font and use default fontset for Unicode font.
  (interactive
   (list (completing-read
          "Font: " (mapcar #'car luna-font-alist))
         (string-to-number (completing-read
                            "Size: " nil nil nil nil nil "13"))))
  (let* ((specs (luna-font-expand-spec font-spec size))
         (ascii (apply #'font-spec (car specs)))
         (cjk (apply #'font-spec (cadr specs))))
    (apply #'set-face-attribute 'default nil :font ascii attrs)
```

The first arg passed to `luna-load-default-font` is a font's NAME instead of a font's SPEC (although in arg it says `font-spec` but actually it is `font-name`), so when you use `(luna-font-expand-spec font-spec size)`, it will throw an error because `luna-font-expand-spec` receives a SPEC intead of a NAME.  What I done is

```diff
-(let* ((specs (luna-font-expand-spec font-spec size))
+(let* ((specs (luna-font-expand-spec
+               (alist-get font-name luna-font-alist nil nil #'equal)
+               size))
```

> And the change to `luna-load-default-font` broke `luna-load-font`.

Sorry, my bad. I only tested `luna-load-default-font` without testing `luna-load-font`😢

**Comment by casouri** [comment]
> The first arg passed to luna-load-default-font is a font's NAME instead of a font's SPEC (although in arg it says font-spec but actually it is font-name), so when you use (luna-font-expand-spec font-spec size), it will throw an error because luna-font-expand-spec receives a SPEC intead of a NAME. What I done is

Where is `luna-load-defaut-font` passed a font name instead of a spec?

> Sorry, my bad. I only tested luna-load-default-font without testing luna-load-font😢

Nah, I wrote buggy code and didn't review carefully 😅

**Comment by dalugm** [comment]
> Where is `luna-load-defaut-font` passed a font name instead of a spec?

https://github.com/casouri/lunarymacs/blob/89580f7ce768a8c4edf77dc03f80ed0f0f6aa90c/site-lisp/lunary.el#L314-L315

Here, it passed a font name instead of a spec

**Comment by casouri** [comment]
Ah, I see, thanks. It should be fixed now.

**Pull request merged**
